asm2/Models/Branch.cs
namespace asm2.Models
{
    public class Branch
    {
        public int BranchId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
    }
}

asm2/Models/ErrorViewModel.cs
namespace asm2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

asm2/Controllers/BranchesController.cs
using asm2.Data;
using asm2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace asm2.Controllers
{
    public class BranchesController : Controller
    {
        private readonly BranchesContext db;

        public BranchesController(BranchesContext context)
        {
            this.db = context;
        }

        public IActionResult Index()
        {
            var branches = db.Branches.ToList();
            return View(branches);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = db.Branches.FirstOrDefault(m => m.BranchId == id);

            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Branch branch)
        {
            branch.State = "Active";
            db.Add(branch);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = db.Branches.Find(id);

            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        [HttpPost]
        public IActionResult Edit(int? id, Branch branch)
        {
            if (id != branch.BranchId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                db.Update(branch);
                db.SaveChanges();

                return RedirectToAction(nameof(Index));
            }

            return View(branch);
        }

        public IActionResult Remove(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = db.Branches.FirstOrDefault(m => m.BranchId == id);

            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        [HttpPost]
        public IActionResult Remove(int? id, Branch branch)
        {
            if (id != branch.BranchId)
            {
                return NotFound();
            }

            db.Remove(branch);
            db.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

asm2/Views/Branches/Add.cshtml
@model asm2.Models.Branch

@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<h4>Branch</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

asm2/Views/Branches/Details.cshtml
@model asm2.Models.Branch

@{
	ViewBag.Title = "Details";
}

<h3>Details</h3>

<div>
	<h4>Branch</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			Ma chi nhanh
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.BranchId)
		</dd>
		<dt class="col-sm-2">
			Ten chi nhanh
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Name)
		</dd>
		<dt class="col-sm-2">
			Dia chi
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Address)
		</dd>
		<dt class="col-sm-2">
			Thanh pho dat chi nhanh
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.City)
		</dd>
		<dt class="col-sm-2">
			Trang thai
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.State)
		</dd>
		<dt class="col-sm-2">
			Ma buu chinh
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ZipCode)
		</dd>
	</dl>
</div>

asm2/Views/Branches/Edit.cshtml
@model asm2.Models.Branch

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Branch</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BranchId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

asm2/Views/Branches/Index.cshtml
@model IEnumerable<asm2.Models.Branch>

@{
    ViewBag.Title = "Branches Page";
}

<h2>Branches</h2>

<p>
    @Html.ActionLink("Add New", "Add")
</p>
<table class="table">
    <tr>
        <th>
            Ma chi nhanh
        </th>
        <th>
            Ten chi nhanh
        </th>
        <th>
            Dia chi
        </th>
        <th>
            Trang thai
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BranchId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.BranchId }) |
                @Html.ActionLink("Details", "Details", new { id=item.BranchId }) |
                @Html.ActionLink("Remove", "Remove", new { id=item.BranchId })
            </td>
        </tr>
    }

</table>

asm2/Views/Branches/Remove.cshtml
@model asm2.Models.Branch

@{
	ViewData["Title"] = "Remove";
}

<h1>Remove</h1>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Are you sure you want to remove this?</h3>
<div>
    <h4>Branch</h4>
    <hr />
	<dl class="row">
		<dt class="col-sm-2">
			Ma chi nhanh
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.BranchId)
		</dd>
		<dt class="col-sm-2">
			Ten chi nhanh
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Name)
		</dd>
		<dt class="col-sm-2">
			Dia chi
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Address)
		</dd>
		<dt class="col-sm-2">
			Thanh pho dat chi nhanh
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.City)
		</dd>
		<dt class="col-sm-2">
			Trang thai
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.State)
		</dd>
		<dt class="col-sm-2">
			Ma buu chinh
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ZipCode)
		</dd>
	</dl>

	<form asp-action="Remove">
        <input type="hidden" asp-for="BranchId" />
		<input type="submit" value="Remove" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

asm2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - asm2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/asm2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">asm2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Branches" asp-action="Index">Branches</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - asm2 - By Nguyen Minh Tri - SE172250
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>